data:
  data_dir: "path_to_your_dataset"
  img_size: [224, 224]
  batch_size: 32
  validation_split: 0.2

visualization:
  enabled: true
  num_samples: 5

model:
  input_shape: [224, 224, 3]
  num_classes: 10
  base_model_trainable: false
  dropout_rate: 0.3

train:
  epochs: 20
  model_save_path: "best_model.keras"

callbacks:
  model_checkpoint:
    enabled: true
  early_stopping:
    enabled: true
    patience: 5
  reduce_lr:
    enabled: true
    factor: 0.2
    patience: 3
    min_lr: 1e-6
